repos:
-   repo: local
    hooks:
    -   id: requirements
        name: requirements
        entry: echo '.\venv-moviesproject\Scripts\pip freeze > requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]

    repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--load-plugins=pylint.extensions.docparams", # Load the docparams plugin
          "--disable=line-too-long,invalid-name,relative-beyond-top-level"
        ]